### PR TITLE
Cleaned up the README and pointed conda instructions to conda forge version.

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
Oops, I now see that this will have conflicts with #19. Didn't realize that.

**Comment by murrayrm** [comment]
@moorepants I finally merged PR #19. If you want to reapply the relevant changes there, please go ahead.  I'm going to generate a release with the current code since this is needed for python-control 0.8.0.

**Comment by moorepants** [comment]
Probably can't get to it till the weekend.

**Comment by murrayrm** [comment]
Superseded by PR #28.

**Pull request closed without merging**
