### PR TITLE
sg03ad parameter N is not hidden by the wrapper

### PR DESCRIPTION
**Pull request by bnavigator**
Minor fix of the docstring. Plus some automatic pep8 fixes done by the IDE (separate commit)

### CODE REVIEW

**Comment by bnavigator** [comment]
[Travis CI fail](https://travis-ci.org/python-control/Slycot/jobs/641992741?utm_medium=notification&utm_source=github_status): another problem with looking up openblas (#85)

```
876 -- A library with LAPACK API found.
786 -- LAPACK: 

...

1705 ImportError: /home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/slycot-0.3.5.11-py3.5-linux-x86_64.egg/slycot/_wrapper.so: undefined symbol: dgebal_
1706 The command "python Slycot/runtests.py --coverage --no-build" exited with 1.

**Comment by murrayrm** [comment]
There are also some alternative fixes in the [conda-forge feedstock](https://github.com/conda-forge/slycot-feedstock/pull/22) for Slycot.

**Comment by bnavigator** [comment]
I don't see anything in there that affects the TravisCI fail not finding it's openblas env on the CONDA=0 job.

#85 or #89 are the way to go.

**Comment by roryyorke** [comment]
All changes look good.

**Pull request merged**
