### PR TITLE
Added wrappers to SLICOT routines AB09BD, SB03BD, SG03BD, AB09MD, AB09ND and SB10DD. Fixed bug in python v3.4 installation

### PR DESCRIPTION
**Pull request by mdclemen**

### CODE REVIEW

**Comment by mdclemen** [comment]
I feel like this is failing because of an issue with the python3.2 build.

**Comment by slivingston** [comment]
Python 3.2 is no longer maintained as of Feb 2016 [1], so I will remove it from the Travis CI test platforms.

[1] https://www.python.org/dev/peps/pep-0392/#lifespan

**Comment by mdclemen** [comment]
I think there is an issue with the Python 3.4 build.

**Comment by slivingston** [comment]
I do not know why Python 3.4 jobs on Travis CI are failing. I first noticed it after merging PR #4 and have been trying to debug it.

**Comment by murrayrm** [comment]
I did a bit of debugging on this.  The problem appears to be that in python 3.4 there is a bug of some sort in numpy and the command `config.add_subpackage('slycot')` in `setup.py` generates an error because it can't fine the module `import.machinery`.  A fix for this is to include that module at the top of `setup.py` using the code:

    # Fix a bug in python v3.4 installation                                         
    if (sys.version_info[0:2] == (3,4)):
        import importlib.machinery

Not sure why this only happens on python 3.4, but if you update to include that fix then we should be able to merge this pull request.

**Comment by mdclemen** [comment]
@murrayrm, thanks for debugging, this should be ready to merge.

**Comment by slivingston** [comment]
@mdclemen did you rebase? The commit messages and authorship appear to be mixed and not valid. Can you try to rebase again? I am available to assist in the process, here or via email.

**Comment by mdclemen** [comment]
I did rebase, what is the issue?

**Comment by slivingston** [comment]
e.g., compare the commit message of https://github.com/python-control/Slycot/pull/2/commits/fa3f9e90a8b000bde7a1ceae230135b580f2b89c with the changes of that commit.

**Comment by murrayrm** [comment]
@slivingston: I'm also confused.  I show that this is read to be merged into master.  I looked at the commit message for fa3f9e9, but didn't see any flags?  What am I missing?

**Comment by mdclemen** [comment]
I undid my rebase.

**Comment by slivingston** [comment]
@mdclemen Thanks! The new rebase is good for me.

@murrayrm The merge would have succeeded, but some of the commit messages were not appropriate for the changesets. The old commits are gone because the rebase was re-done, so I cannot furnish evidence unless the Web Archive or some other site captured them.

**Comment by murrayrm** [comment]
Thanks @slivingston. I'll leave to you to merge since you are the assignee -:).

**Comment by slivingston** [comment]
@mdclemen In the future, the pull request should include tests. In the case of newly wrapped routines, tests should be provided that check expected behavior, e.g., as in `test_sb02ad` [in slycot/tests/test.py](https://github.com/python-control/Slycot/blob/a1f66bc2ed881c79c743ea76922e060fb5e637be/slycot/tests/test.py#L19)

Currently there is little testing, so I think it is OK to merge changes from here and, then, work on improving test coverage for the entire package.

**Pull request merged**
