### PR TITLE
Work on build system

### PR DESCRIPTION
**Pull request by repagh**
Cleaned up conda build configurations
Use the BLA_VENDOR flag to explicitly select a blas type
Should address issue https://github.com/conda-forge/slycot-feedstock/issues/23
Backports the work in the patch on https://github.com/conda-forge/slycot-feedstock/pull/22

### CODE REVIEW

**Comment by bnavigator** [comment]
Excellent. It's nice to see progress on the build system and some clarification on the use of different lapack/blas packages

commits 009a2b8 and ba2b2f9 for the mb03rd wrapper should not be part of this PR. Can you rebase?

**Comment by bnavigator** [comment]
removing the mb03rd (belongs to #73) commits should also resolve some of the failing Travis jobs:

```
1710 ======================================================================
1711 ERROR: Failure: ModuleNotFoundError (No module named 'scipy')
1712 ----------------------------------------------------------------------
```

**Comment by bnavigator** [comment]
Update: I forked [your branch and rebased it](https://github.com/bnavigator/Slycot/tree/work-on-build-system) onto master, so the Travis jobs don't fail with the scipy error anymore. However there are some problems with finding the correct LAPACK/Blas/OpenBLAS/MKL libraries.

https://travis-ci.org/bnavigator/Slycot/builds/644882207

- 27.2 (Python 2.7, TEST_CONDA=1) 
 `ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory`
- 27.3 (Python 3.5, TEST_CONDA=0)
 `ImportError: /home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/slycot-0.3.5.13-py3.5-linux-x86_64.egg/slycot/_wrapper.cpython-35m-x86_64-linux-gnu.so: undefined symbol: dgebal_`

and so on.

**Comment by repagh** [comment]
messed this up. Starting anew

**Comment by bnavigator** [comment]
Hey @repagh, I just rebased minutes before your rebase going wrong. Should I submit my branch https://github.com/bnavigator/Slycot/tree/work-on-build-system
as the new PR? It still has your commits authored by you.

**Comment by repagh** [comment]
ok, thanks

**Pull request closed without merging**
