### PR TITLE
Merge conda recipes

### PR DESCRIPTION
**Pull request by bnavigator**
Merge all conda recipes into one. This builds on top of #142.

- In conda, only compile against the NETLIB headers.
  *  https://conda-forge.org/docs/maintainer/knowledge_base.html#blas
  *  https://github.com/conda-forge/slycot-feedstock/issues/23
- Test with different installed LAPACK/BLAS implementation libraries.

### CODE REVIEW

**Comment by roryyorke** [comment]
LGTM.  I'll leave it to you to merge, so you can decide on sequence of this vs #140.

**Comment by bnavigator** [comment]
Let's give @repagh some time to chime in.

**Comment by bnavigator** [comment]
I changed some README paragraphs reflecting the new merged conda recipe situation.

With Python 3.6+ The windows compiler is the same for all versions.

**Comment by roryyorke** [comment]
This is now part of #140?

**Comment by bnavigator** [comment]
Not necessarily. The branch for #140 just is based on this branch. So merge this first, then #140. Or, if #140 is merged, this PR will automatically be merged as well.

**Pull request merged**
