### PR TITLE
Work around numpy/numpy#21889

### PR DESCRIPTION
**Pull request by bnavigator**
Works around numpy/numpy#21889 as reported in #177

### CODE REVIEW

**Comment by matthieuvigne** [comment]
Looks like a nice workaround for now, until numpy is fixed!

I think you should tag & publish it on pip to have it working again. As is, I tried the install on ubuntu and fedora, and tried installing older versions of slycot - but obviously nothing worked since the issue was with numpy all along :)

**Comment by bnavigator** [comment]
Thanks @matthieuvigne 

Yes, we need a new release. It's been over two years since 4.0.0 already and we made quite some fixes and enhancements.

I don't have access to the pypi credentials thoug. Any thoughts @roryyorke?

**Comment by roryyorke** [comment]
No objections from me. I'll have some time Sunday or next weekend.

**Comment by roryyorke** [comment]
Ran out of time today, sorry. Should have some time next weekend.

**Pull request merged**
